# whitelisted branches
branches:
  only:
    - docs
    
language: python

python:
  - "2.7"
  
install: 
  - npm run install

script: 
  - npm run get-wiki
  - npm run build

deploy:
  provider: surge
  project: ./site/
  skip_cleanup: true
  on:
    branch: docs
  edge:
    source: mathiasrw/dpl
    branch: master


